### ISSUE TITLE
Uploading a folder with more than 100 files

### ISSUE THREAD

**Issue by yoyoprs** [flowjs/flow.js#89]
When I upload a folder (with chrome) containing +700 files, only the first 100 files are sent.
In all cases this limit of 100 files is applied.

**Comment by AidasK** [comment]
https://github.com/23/resumable.js/pull/219
Maybe similar issue?

**Comment by yoyoprs** [comment]
yes

**Comment by bneigher** [comment]
It appears that this is still not fixed.  Has anyone had any success with this?

**Comment by evilaliv3** [comment]
@bneigher could you provide details of your setup? with which browser are you testing?

when filing issues it's important to provide us details so that we can reproduce the bugs. thanks

**Comment by bneigher** [comment]
Sure.  I am using Chrome Version 47.0.2526.111 (64-bit) on Mac OS X 10.11.2.

After testing @roccivic's commit on his forked flow.js, I have determined that his changes are legit and fix the issue.  Perhaps his code should be merged into here?

In particular, the issue is occurs on the drop of the folder.

**Comment by evilaliv3** [comment]
that patch has been merge in https://github.com/flowjs/flow.js/commit/36c18fadd034d5b6950bc6ad30f1022959ff77b6

@roccivic do you have any hint on what can have introduced the regression? would you please retest current build?

**Comment by roccivic** [comment]
@evilaliv3 No idea what might be causing this. And I can't reproduce the issue at c375a348a5d0b630777809fdd2378008d6777a0f.

Tested:
* using drag and drop
* Chrome 48.0.2564.97 m
* Windows 8.1 x64
* using angular 1.4.9 and ng-flow 2.7.1

**Comment by bneigher** [comment]
Ah man, I was pointing to the wrong release.  It is indeed fixed.  No wonder the code looked different.
I think this is fixed, should close the issue.  Thanks for looking into this

**Comment by stramel** [comment]
Is this closed?

**Comment by AidasK** [comment]
Should be fixed, please reopen if it is not.

**Comment by Electromaxim** [comment]
Still can not upload a folder with 100+ (small) files. 
With Chrome/Opera it gives: "Yowza, that’s a lot of files. Try again with fewer than 100 files."
Firefox doesn`t react at all. I`m using aws ec2 on win

**Comment by Krafty-Coder** [comment]
I'm using Ubuntu gnome 
Mozilla browser and still cant upload more than 100 files.
Even drag and drop doesn't work for me
First tried with chrome but still no luck in trying to upload
Any helpful way of doing this?

**Comment by pcstraw** [comment]
I'm encountering the 100 file size limit as well on Chrome.

**Comment by vdiaza** [comment]
Hi, I have been using resumablejs, and this issue exists there, was this addressed in this library?
